BROKER_URL = "localhost"
VITALS_EXCHANGE_NAME = "vitals"
REPLICA_EXCHANGE_NAME = "replica"
REPLICA_QUEUE_NAME = "replica_queue"
INTERVAL_VITALS_REPORT = 3
REPLICA_FACTOR = 2
SHARD_SIZE = 1024 * 1024 * 64 # 64 MB
NUM_THREADS_DOWNLOAD = 4
